# Generated by Django 4.2.15 on 2024-08-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='angus', max_length=100),
            preserve_default=False,
        ),
    ]
