# Generated by Django 4.2.15 on 2024-08-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
    ]
