# Generated by Django 4.2.15 on 2024-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_supplier_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
