# Generated by Django 4.2.15 on 2024-08-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_order_id_orderdetail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='barcode',
        ),
    ]
