# Generated by Django 4.2.15 on 2024-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_orderdetail_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
