# Generated by Django 4.2.15 on 2024-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_item_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backorder',
        ),
    ]
