# Generated by Django 4.2.15 on 2024-08-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
